name: Auto Download Game Images

on:
  issues:
    types: [opened, edited, labeled]

jobs:
  download-image:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'image-request') && !contains(github.event.issue.labels.*.name, 'completed') && !contains(github.event.issue.labels.*.name, 'processing')
    
    steps:
      - name: Add processing label
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['processing']
            });
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🔄 Processing image download request...'
            });
      
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}
        continue-on-error: true
      
      - name: Check checkout
        if: steps.checkout.outcome != 'success'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ Failed to checkout repository. Manual intervention required.'
            });
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['needs-manual-intervention']
            });
            github.rest.issues.removeLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ['processing']
            });
        continue-on-error: true
      
      - name: Extract image information
        if: steps.checkout.outcome == 'success'
        id: extract
        shell: bash
        run: |
          # Usa una variabile temporanea per il corpo dell'issue
          BODY="${{ github.event.issue.body }}"
          echo "Issue body: $BODY"
          
          # Verifica se l'URL dell'immagine è nel formato corretto con regex più sicuro
          IMAGE_URL=$(echo "$BODY" | grep -o 'Image URL: http[s]*://[^ ]*' | sed 's/Image URL: //')
          echo "Extracted image URL: $IMAGE_URL"
          
          # Estrai nome del file in modo sicuro
          TARGET_FILENAME=$(echo "$BODY" | grep -o 'Target filename: `[^`]*`' | sed 's/Target filename: `//' | sed 's/`//')
          echo "Target filename from issue: $TARGET_FILENAME"
          
          # Se target filename non è stato trovato, estrai il nome del gioco e sanitizzalo
          if [ -z "$TARGET_FILENAME" ]; then
            GAME_NAME=$(echo "$BODY" | grep -o 'Game: [^\n]*' | sed 's/Game: //')
            echo "Game name: $GAME_NAME"
            
            if [ -n "$GAME_NAME" ]; then
              # Sanitizza il nome del gioco per il nome file in modo sicuro
              SANITIZED_NAME=$(echo "$GAME_NAME" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/_/g')
              TARGET_FILENAME="${SANITIZED_NAME}.jpg"
              echo "Generated target filename: $TARGET_FILENAME"
            fi
          fi
          
          # Salva i risultati in output variables usando sintassi moderna
          if [ -n "$IMAGE_URL" ]; then
            echo "image_url=$IMAGE_URL" >> $GITHUB_OUTPUT
          else
            echo "image_url=" >> $GITHUB_OUTPUT
          fi
          
          if [ -n "$TARGET_FILENAME" ]; then
            echo "target_filename=$TARGET_FILENAME" >> $GITHUB_OUTPUT
          else
            echo "target_filename=" >> $GITHUB_OUTPUT
          fi
          
          if [ -n "$GAME_NAME" ]; then
            echo "game_name=$GAME_NAME" >> $GITHUB_OUTPUT
          else
            echo "game_name=" >> $GITHUB_OUTPUT
          fi
      
      - name: Validate extraction
        if: steps.checkout.outcome == 'success'
        id: validate
        run: |
          if [ -z "${{ steps.extract.outputs.image_url }}" ]; then
            echo "valid=false" >> "$GITHUB_OUTPUT"
            echo "reason=No image URL found in issue body" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          
          if [ -z "${{ steps.extract.outputs.target_filename }}" ]; then
            echo "valid=false" >> "$GITHUB_OUTPUT"
            echo "reason=No target filename could be determined" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          
          echo "valid=true" >> "$GITHUB_OUTPUT"
      
      - name: Report invalid extraction
        if: steps.checkout.outcome == 'success' && steps.validate.outputs.valid != 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `❌ Could not process image request: ${{ steps.validate.outputs.reason }}. Please check the issue format.`
            });
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['needs-manual-intervention']
            });
            github.rest.issues.removeLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ['processing']
            });
      
      - name: Download image
        if: steps.checkout.outcome == 'success' && steps.validate.outputs.valid == 'true'
        id: download
        run: |
          mkdir -p images
          FILENAME="${{ steps.extract.outputs.target_filename }}"
          URL="${{ steps.extract.outputs.image_url }}"
          
          echo "Downloading image from $URL to images/$FILENAME"
          HTTP_CODE=$(curl -L "$URL" -o "images/$FILENAME" -w "%{http_code}")
          echo "http_code=$HTTP_CODE" >> "$GITHUB_OUTPUT"
          
          if [ "$HTTP_CODE" == "200" ]; then
            echo "success=true" >> "$GITHUB_OUTPUT"
            echo "Image downloaded to images/$FILENAME"
            ls -la images/
          else
            echo "success=false" >> "$GITHUB_OUTPUT"
            echo "Failed to download image, HTTP code: $HTTP_CODE"
          fi
      
      - name: Report download failure
        if: steps.checkout.outcome == 'success' && steps.validate.outputs.valid == 'true' && steps.download.outputs.success != 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `❌ Failed to download image from URL. HTTP Status: ${{ steps.download.outputs.http_code }}. Manual intervention required.`
            });
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['needs-manual-intervention']
            });
            github.rest.issues.removeLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ['processing']
            });
      
      - name: Commit and push changes
        if: steps.checkout.outcome == 'success' && steps.validate.outputs.valid == 'true' && steps.download.outputs.success == 'true'
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          FILENAME="${{ steps.extract.outputs.target_filename }}"
          git add "images/$FILENAME"
          git commit -m "Add image for ${{ steps.extract.outputs.game_name || steps.extract.outputs.target_filename }}"
          
          # Usa nuovo formato per gli output in GitHub Actions
          echo "success=true" >> $GITHUB_OUTPUT
          
          # Push utilizzando il token di autenticazione
          git push origin HEAD:main || git push
        continue-on-error: true
      
      - name: Report commit failure
        if: steps.checkout.outcome == 'success' && steps.validate.outputs.valid == 'true' && steps.download.outputs.success == 'true' && steps.commit.outcome != 'success'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `❌ Failed to commit the image to repository. Manual intervention required.`
            });
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['needs-manual-intervention']
            });
            github.rest.issues.removeLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ['processing']
            });
      
      - name: Complete successfully
        if: steps.checkout.outcome == 'success' && steps.validate.outputs.valid == 'true' && steps.download.outputs.success == 'true' && steps.commit.outcome == 'success'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ Image has been successfully downloaded and added to the repository as `images/${{ steps.extract.outputs.target_filename }}`.'
            });
            github.rest.issues.update({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'closed',
              labels: ['image-request', 'automated', 'completed']
            });
            github.rest.issues.removeLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ['processing']
            });