name: Auto Download Game Images

on:
  issues:
    types: [opened, edited, labeled]

permissions:
  contents: write
  issues: write

jobs:
  download-image:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'image-request') && !contains(github.event.issue.labels.*.name, 'completed')
    
    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false # Importante: non persistere le credenziali predefinite
          fetch-depth: 0
      
      - name: Extract image information
        id: extract
        shell: bash
        run: |
          # Scrivi il corpo dell'issue in un file per debug
          echo "Corpo dell'issue:"
          echo '${{ github.event.issue.body }}'
          echo "-----------------------------------"
          
          # Memorizza il corpo dell'issue in un file temporaneo senza interpretazione
          echo '${{ github.event.issue.body }}' > issue_body.txt
          
          # Extra debug
          echo "Contenuto di issue_body.txt:"
          cat issue_body.txt
          echo "-----------------------------------"
          
          # Usa comandi più sicuri per estrarre i dati
          # Estrazione dell'URL dell'immagine
          IMAGE_URL=$(grep -o 'Image URL: [^ ]*' issue_body.txt | cut -d' ' -f3- || echo "")
          echo "URL dell'immagine estratto: ${IMAGE_URL}"
          
          # Estrazione del nome del file target
          TARGET_FILENAME=""
          if grep -q "Target filename:" issue_body.txt; then
            # Gestione speciale per estrarre il contenuto tra backticks
            TARGET_LINE=$(grep "Target filename:" issue_body.txt)
            # Cerca tutto dopo `Target filename: ` fino alla fine della riga
            TARGET_FILENAME=$(echo "$TARGET_LINE" | sed -E 's/.*Target filename: `?([^`]*)`?.*/\1/')
            echo "Nome file target estratto: ${TARGET_FILENAME}"
          fi
          
          # Estrazione del nome del gioco
          GAME_NAME=""
          if [ -z "$TARGET_FILENAME" ] && grep -q "Game:" issue_body.txt; then
            GAME_LINE=$(grep "Game:" issue_body.txt)
            GAME_NAME=$(echo "$GAME_LINE" | sed -E 's/.*Game: (.*)/\1/')
            echo "Nome del gioco estratto: ${GAME_NAME}"
            
            if [ -n "$GAME_NAME" ]; then
              SANITIZED_NAME=$(echo "$GAME_NAME" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/_/g')
              TARGET_FILENAME="${SANITIZED_NAME}.jpg"
              echo "Nome file target generato: ${TARGET_FILENAME}"
            fi
          fi
          
          # Verifica che tutte le variabili necessarie siano state estratte correttamente
          if [ -z "$IMAGE_URL" ]; then
            echo "ERRORE: URL dell'immagine non trovato!"
          fi
          
          if [ -z "$TARGET_FILENAME" ]; then
            echo "ERRORE: Nome del file target non trovato!"
          fi
          
          # Salva i risultati in modo sicuro
          echo "image_url=${IMAGE_URL}" >> "$GITHUB_OUTPUT"
          echo "target_filename=${TARGET_FILENAME}" >> "$GITHUB_OUTPUT"
          echo "game_name=${GAME_NAME}" >> "$GITHUB_OUTPUT"
      
      - name: Download image
        if: steps.extract.outputs.image_url != '' && steps.extract.outputs.target_filename != ''
        id: download
        run: |
          mkdir -p images
          curl -L "${{ steps.extract.outputs.image_url }}" -o "images/${{ steps.extract.outputs.target_filename }}"
          echo "Image downloaded to images/${{ steps.extract.outputs.target_filename }}"
          ls -la images/
          echo "success=true" >> "$GITHUB_OUTPUT"
      
      - name: Commit and push changes
        if: steps.extract.outputs.image_url != '' && steps.extract.outputs.target_filename != ''
        id: commit
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          FILENAME="${{ steps.extract.outputs.target_filename }}"
          git add "images/$FILENAME" || echo "No changes to commit"
          git commit -m "Add image for ${{ steps.extract.outputs.game_name || steps.extract.outputs.target_filename }}" || echo "No changes to commit"
          
          # Utilizzo di un token di deploy con permessi di scrittura
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}
          git push || echo "Nothing to push"
          echo "success=true" >> "$GITHUB_OUTPUT"
      
      - name: Comment on issue
        if: steps.extract.outputs.image_url != '' && steps.extract.outputs.target_filename != '' && steps.download.outputs.success == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ Image has been automatically downloaded and added to the repository as `images/${{ steps.extract.outputs.target_filename }}`.'
            });
            github.rest.issues.update({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'closed',
              labels: ['image-request', 'automated', 'completed']
            });
      
      - name: Comment on error
        if: failure() || (steps.extract.outputs.image_url == '') || (steps.extract.outputs.target_filename == '')
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ Failed to automatically download and add the image. Manual intervention required.'
            });
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['needs-manual-intervention']
            });